### PR TITLE
Adding a SVG icon.

### PR DESCRIPTION
**Pull request by lucaboesch**

### CODE REVIEW

**Comment by learningtechnologyservices** [comment]
We are about to change the icon - will update this coming week.

**Comment by lucaboesch** [comment]
Thanks Karen, that's fantastic!

Just one more thing, I think you have got a kind of https://tracker.moodle.org/browse/MDL-64757 situation because if you switch to another locale the column headings in a new Bard appear as "Heading" even if the page language is a different one from english.
I know I should have reported this elsewhere – sorry!

**Comment by learningtechnologyservices** [comment]
Well, heading is the text default - it shouldnt change.  If you put Bob in there it would not change!

(oh, and this was Gavin replying as karens account as with others - bold me.)

**Comment by lucaboesch** [comment]
Sorry Gavin, on a second check everything was all good.

**Pull request closed without merging**
