### PR TITLE
Feature/svg

### PR DESCRIPTION
**Pull request by andreasschenkel**
now settings support of accepted filetypes for backgroundimage and contentimages (jpg, jpeg, png, bmp, svg)

### CODE REVIEW

**Comment by andreasschenkel** [comment]
With this code an admin gets two new settings in the website-administration to configuration the plugin.
One setting is for selecting the allowed filetypes for background images. 
The second setting is for selecting the allowed filetypes that can be used by the students as a board-content.
In addition the svg is a new filetype, that can be selected if wanted.

**Comment by andreasschenkel** [comment]
I have forgotten to add gif to the supported filetypes.

**Comment by mchurchward** [comment]
For clarity, this is a continuation of https://github.com/brickfield/moodle-mod_board/pull/27

**Comment by mchurchward** [comment]
I'm having issues with this. If I deselect one of the accepted types (e.g. svg), and then I add an image to the board, I get an exception but without any message as to why. In the previous version, if I uploaded an invalid type, I got an exception that included a message that indicted the file type was invalid.
There might be an issue with the way the message is formed as I do get this:
"Error code: formsubmissioninvalid
$a contents:"

**Comment by andreasschenkel** [comment]
The extensions should be defined without a leading dot because in the code the dot is added.
Please use this ne pull request.

**Comment by learningtechnologyservices** [comment]
Hi @andreasschenkel , many thanks for your discussion and code contributions here, we've implemented your [SVG and GIF support settings here](https://github.com/brickfield/moodle-mod_board/commit/05d0a51a000482e431c6a1adbccef14d96cdfd42), so I'm going to close this issue!

**Pull request closed without merging**
